cd C:\CHEQUEO_EXTERNAS\IMPORTA TABLAS\dist\IMPORTA_TABLAS
IMPORTA_TABLAS.exe
cd C:\CHEQUEO_EXTERNAS\\EXTERNAS EN ERI2G_PROD
EJECUTA_CHEQUEOS.bat
cd C:\CHEQUEO_EXTERNAS\\EXTERNAS EN ERI3G_PROD
EJECUTA_CHEQUEOS.bat
cd C:\CHEQUEO_EXTERNAS\\EXTERNAS EN HUA2G_PROD
EJECUTA_CHEQUEOS.bat
cd C:\CHEQUEO_EXTERNAS\\EXTERNAS EN HUA3G_PROD
EJECUTA_CHEQUEOS.bat
cd C:\CHEQUEO_EXTERNAS\\EXTERNAS EN RED SHARING
EJECUTA_CHEQUEOS.bat

